# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu-18.04"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.ssh.pty = true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.inventory_path = "inventory/vagrant"
  end

end
